#!/bin/bash

# changelog-gen.sh - Generate beautiful changelogs from emoji commits
# Part of the Aesthetics toolkit

set -e

usage() {
    echo "📋 changelog-gen.sh - Generate changelogs from emoji commits"
    echo ""
    echo "Usage: $0 [options]"
    echo ""
    echo "Options:"
    echo "  -s, --since TAG    Start from tag/commit (default: beginning)"
    echo "  -u, --until TAG    End at tag/commit (default: HEAD)"
    echo "  -f, --format FMT   Output format: md, json (default: md)"
    echo "  -o, --output FILE  Output file (default: stdout)"
    echo "  -h, --help         Show this help message"
    echo ""
    echo "Example:"
    echo "  $0 --since v1.0.0 --format md"
    echo "  $0 --since v1.0.0 --until v2.0.0 --output CHANGELOG.md"
    exit 0
}

# Defaults
SINCE=""
UNTIL="HEAD"
FORMAT="md"
OUTPUT=""

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        -s|--since) SINCE="$2"; shift 2 ;;
        -u|--until) UNTIL="$2"; shift 2 ;;
        -f|--format) FORMAT="$2"; shift 2 ;;
        -o|--output) OUTPUT="$2"; shift 2 ;;
        -h|--help) usage ;;
        *) shift ;;
    esac
done

# Verify git repo
if ! git rev-parse --git-dir > /dev/null 2>&1; then
    echo "❌ Error: Not a git repository" >&2
    exit 1
fi

# Build git range
if [[ -n "$SINCE" ]]; then
    RANGE="${SINCE}..${UNTIL}"
else
    RANGE="$UNTIL"
fi

# Emoji categories
declare -A CATEGORIES
CATEGORIES["🎉"]="🎉 Initial"
CATEGORIES["✨"]="✨ Features"
CATEGORIES["🐛"]="🐛 Bug Fixes"
CATEGORIES["🔥"]="🔥 Removed"
CATEGORIES["📝"]="📝 Documentation"
CATEGORIES["🚀"]="🚀 Deployment"
CATEGORIES["💄"]="💄 UI/Style"
CATEGORIES["♻️"]="♻️ Refactoring"
CATEGORIES["🔧"]="🔧 Configuration"
CATEGORIES["✅"]="✅ Tests"
CATEGORIES["🔒"]="🔒 Security"
CATEGORIES["⬆️"]="⬆️ Dependencies"
CATEGORIES["⬇️"]="⬇️ Dependencies"
CATEGORIES["🏗️"]="🏗️ Architecture"
CATEGORIES["📦"]="📦 Build"
CATEGORIES["🔀"]="🔀 Merges"
CATEGORIES["🚧"]="🚧 Work in Progress"
CATEGORIES["🚑"]="🚑 Hotfixes"
CATEGORIES["⏪"]="⏪ Reverts"
CATEGORIES["💚"]="💚 CI"
CATEGORIES["👷"]="👷 CI"

# Get category for emoji
get_category() {
    local emoji="$1"
    echo "${CATEGORIES[$emoji]:-📌 Other}"
}

# Generate markdown
generate_md() {
    local repo_name=$(basename "$(pwd)")
    local date=$(date +%Y-%m-%d)
    
    echo "# Changelog"
    echo ""
    echo "_Generated on ${date}_"
    echo ""
    
    if [[ -n "$SINCE" ]]; then
        echo "## Changes from ${SINCE} to ${UNTIL}"
    else
        echo "## All Changes"
    fi
    echo ""
    
    # Group commits by emoji category
    declare -A grouped
    
    while IFS='|' read -r hash date author msg; do
        # Extract first emoji
        emoji=$(echo "$msg" | grep -oE "^[🎉✨🐛🔥📝🚀💄♻️🔧✅🔒⬆️⬇️🏗️📦🔀🚧🚑⏪💚👷📌]" | head -1)
        
        if [[ -z "$emoji" ]]; then
            emoji="📌"
        fi
        
        category=$(get_category "$emoji")
        
        # Clean message (remove emoji prefix if present)
        clean_msg=$(echo "$msg" | sed 's/^[^a-zA-Z0-9]*//')
        
        if [[ -z "${grouped[$category]}" ]]; then
            grouped[$category]=""
        fi
        grouped[$category]+="- ${clean_msg} (\`${hash}\`)"$'\n'
        
    done < <(git log "$RANGE" --format="%h|%as|%an|%s" 2>/dev/null)
    
    # Output grouped
    for category in "✨ Features" "🐛 Bug Fixes" "📝 Documentation" "♻️ Refactoring" "🔧 Configuration" "✅ Tests" "🔒 Security" "⬆️ Dependencies" "🏗️ Architecture" "📦 Build" "🚑 Hotfixes" "📌 Other"; do
        if [[ -n "${grouped[$category]}" ]]; then
            echo "### ${category}"
            echo ""
            echo "${grouped[$category]}"
        fi
    done
    
    echo "---"
    echo ""
    echo "_Generated by [aesthetics](https://github.com/nirholas/aesthetics)_"
}

# Generate JSON
generate_json() {
    echo "{"
    echo "  \"generated\": \"$(date -Iseconds)\","
    echo "  \"repository\": \"$(basename "$(pwd)")\","
    echo "  \"range\": \"${RANGE}\","
    echo "  \"commits\": ["
    
    local first=true
    while IFS='|' read -r hash date author msg; do
        if [[ "$first" != "true" ]]; then
            echo ","
        fi
        first=false
        
        # Escape JSON
        msg=$(echo "$msg" | sed 's/"/\\"/g')
        author=$(echo "$author" | sed 's/"/\\"/g')
        
        printf '    {"hash": "%s", "date": "%s", "author": "%s", "message": "%s"}' "$hash" "$date" "$author" "$msg"
        
    done < <(git log "$RANGE" --format="%h|%as|%an|%s" 2>/dev/null)
    
    echo ""
    echo "  ]"
    echo "}"
}

# Generate output
if [[ "$FORMAT" == "json" ]]; then
    if [[ -n "$OUTPUT" ]]; then
        generate_json > "$OUTPUT"
        echo "✅ Changelog written to $OUTPUT"
    else
        generate_json
    fi
else
    if [[ -n "$OUTPUT" ]]; then
        generate_md > "$OUTPUT"
        echo "✅ Changelog written to $OUTPUT"
    else
        generate_md
    fi
fi


